### ISSUE TITLE
events.js:377       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by YoannBuzenet** [justinribeiro/devtools-to-video#6]
Hello,

I installed your package. When I run `npx devtools-to-video -i trace.json -o sample5.mp4 -l '3G Slow @ Moto G4'`, I get the following error : 

```
STARTING UP  Checking environment and setting up params.
 CONVERT  Spawning FFMPEG worker with open pipe.
 CONVERT  Begin piping screenshots from DevTools trace to FFMPEG.
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-framerate',
    '60',
    '-f',
    'image2pipe',
    '-vcodec',
    'mjpeg',
    '-i',
    '-',
    '-hide_banner',
    '-loglevel',
    'panic',
    '/tmp/JDR-DEVTOOLS-45835gtdPV9XuBQID.mp4'
  ]
}
```

The file is a `trace.json` created by Chromium.
Would you know what could happen ? I am on Linux, maybe I a missing some codecs ?

Thank you for your package
Yoann

**Comment by YoannBuzenet** [comment]
It was the ffmpeg package missing on my linux distribution.

I corrected it with `sudo snap install ffmpeg`
