### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by YoannBuzenet** [justinribeiro/devtools-to-video#7]
Hello,

Sorry for the double posting your issue section the same day. I found that ffmpeg package was missing on my linux distribution.

After adding it, I have this new error :  
```
npx devtools-to-video -i trace.json -o sample5.mp4 -l '3G Slow @ Moto G4'
 STARTING UP  Checking environment and setting up params.
 CONVERT  Spawning FFMPEG worker with open pipe.
 CONVERT  Begin piping screenshots from DevTools trace to FFMPEG.
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

Would you know where it comes from ?

Thanks,
Yoann

**Comment by YoannBuzenet** [comment]
It corrected after passing to node 16 (I was on 14)

Thank your for this lib. It works nicely !
